### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by PandoricGalaxy** [DevMystical/Obfuscator#3]
![image](https://user-images.githubusercontent.com/86944806/169980682-1aefee80-1018-4042-b412-1cf6a1f13700.png)

I tried converting the obfuscated file to exe using nuitika and this error occured.

**Comment by DevMystical** [comment]
What does your input script look like? The conversion to .exe should not impact the behavior of the script which leads me to believe that the script you are obfuscating contains a recursive function that is going unchecked. A recursive function is one which calls itself, and python does not allow this to happen more than 1000 times. If you are not sure where this would happen in your script you can send it to me on discord and I'll take a look.

```py
def recursive_function():
    recursive_function()
```

**Comment by PandoricGalaxy** [comment]
it happens since im obfuscating the code

**Comment by DevMystical** [comment]
The obfuscator raises that error when obfuscating your script?

**Comment by PandoricGalaxy** [comment]
no the obfuscation has no errors this happens when trying to convert the obfuscated file to .exe

**Comment by PandoricGalaxy** [comment]
I used this to convert the file into .exe

`nuitka --mingw64 --windows-disable-console --onefile obf.py`

**Comment by DevMystical** [comment]
Unfortunately due to the nature of this obfuscator, it creates output files that are incredibly large. For your use case which appears to be a complex token logger, I would recommend two things. 

First, skip my obfuscator because the purpose of it is to be able to give .py files to people which look insane. It does not add a ton of security and was mostly a small project that I created for fun. Your script can be turned directly into a .exe and will run **much** faster and more efficiently.

Second, no matter how much you obfuscate or compile your program, the webhook can be reverse engineered just by listening to the network traffic when it runs. If you have a way to ship this program and are planning on releasing it, etc, I implore that you purchase a VPS, ideally in the Netherlands, Switzerland, etc. On this VPS host an API which hides the webhook but still allows normal data to be sent to it. Anyone can delete a webhook if they know the URL, and this will protect your program.

It seems my program might not be the best tool to use for what you are working on. If you have questions on anything I asked about please contact me on discord at Mystical#5113.

**Comment by PandoricGalaxy** [comment]
thanks for the help!
